apiVersion: v1
kind: Pod
metadata:
  name: multi-cont
  labels:
    pod: multi-cont
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: multi-cont-vol
          mountPath: /usr/share/nginx/html
    - name: cont2
      image: centos:latest
      command: [ "sh", "-c", "date > /data/file.txt && sleep 1000" ]
      volumeMounts:
        - name: multi-cont-vol
          mountPath: /data
  volumes:
    - name: multi-cont-vol
      hostPath:
        path: /adhamk8s
        type: Directory
